import {
  UserProfile,
  Conversation,
  ChatMessage,
  StatusItem,
  ProductItem,
  EventItem,
  JobItem,
  CommunityItem,
  WalletTransaction,
  NotificationItem,
} from '../../types';

export const INITIAL_USER: UserProfile = {
  id: 'current_user_id',
  email: 'savegamour@gmail.com',
  displayName: 'Amina Kaunga',
  username: 'amina_kaunga',
  photoURL: '/assets/images/amina_avatar_1790280951312.jpg',
  bio: 'Content Creator | Fashion | Lifestyle\nDream • Create • Inspire',
  accountType: 'creator',
  verified: true,
  followersCount: 12400,
  followingCount: 245,
  postsCount: 3200,
  isOnline: true,
  lastSeen: 'Just now',
};

export const INITIAL_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv_1',
    participants: ['current_user_id', 'user_sarah'],
    participantDetails: {
      user_sarah: {
        displayName: 'Sarah Mwangi',
        photoURL: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=500&auto=format&fit=crop&q=80',
        username: 'sarah_m',
        isOnline: true,
      },
    },
    isGroup: false,
    lastMessage: 'Hey! How are you doing? 😊',
    lastMessageSenderId: 'user_sarah',
    lastMessageType: 'text',
    updatedAt: '2m ago',
    unreadCount: 1,
  },
  {
    id: 'conv_2',
    participants: ['current_user_id', 'user_design_team'],
    isGroup: true,
    groupName: 'Design Team',
    groupAvatar: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=500&auto=format&fit=crop&q=80',
    lastMessage: 'File uploaded: project_final.psd',
    lastMessageSenderId: 'user_james',
    lastMessageType: 'document',
    updatedAt: '12m ago',
    unreadCount: 0,
  },
  {
    id: 'conv_3',
    participants: ['current_user_id', 'user_family'],
    isGroup: true,
    groupName: 'Family Group',
    groupAvatar: 'https://images.unsplash.com/photo-1511895426328-dc8714191300?w=500&auto=format&fit=crop&q=80',
    lastMessage: 'Mama: Karibu nyumbani!',
    lastMessageSenderId: 'user_mama',
    lastMessageType: 'text',
    updatedAt: '18m ago',
    unreadCount: 2,
  },
  {
    id: 'conv_4',
    participants: ['current_user_id', 'user_alex'],
    participantDetails: {
      user_alex: {
        displayName: 'Alex Johnson',
        photoURL: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&auto=format&fit=crop&q=80',
        username: 'alex_j',
        isOnline: true,
      },
    },
    isGroup: false,
    lastMessage: 'Typing...',
    lastMessageSenderId: 'user_alex',
    lastMessageType: 'text',
    updatedAt: '24m ago',
    unreadCount: 0,
  },
  {
    id: 'conv_5',
    participants: ['current_user_id', 'user_market'],
    participantDetails: {
      user_market: {
        displayName: 'Market Place Support',
        photoURL: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=500&auto=format&fit=crop&q=80',
        username: 'marketplace_hq',
        isOnline: false,
      },
    },
    isGroup: false,
    lastMessage: 'New product available: Wireless Earbuds',
    lastMessageSenderId: 'user_market',
    lastMessageType: 'text',
    updatedAt: '32m ago',
    unreadCount: 0,
  },
  {
    id: 'conv_6',
    participants: ['current_user_id', 'user_travel'],
    isGroup: true,
    groupName: 'Travel Buddies',
    groupAvatar: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=500&auto=format&fit=crop&q=80',
    lastMessage: "Jane: Let's plan the Zanzibar trip",
    lastMessageSenderId: 'user_jane',
    lastMessageType: 'text',
    updatedAt: '1h ago',
    unreadCount: 0,
  },
];

export const INITIAL_MESSAGES_CONV2: ChatMessage[] = [
  {
    id: 'msg_1',
    conversationId: 'conv_2',
    senderId: 'user_james',
    senderName: 'James',
    senderAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&auto=format&fit=crop&q=80',
    text: 'The new design is amazing!',
    messageType: 'text',
    createdAt: '10:24',
  },
  {
    id: 'msg_2',
    conversationId: 'conv_2',
    senderId: 'user_aisha',
    senderName: 'Aisha',
    senderAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=500&auto=format&fit=crop&q=80',
    text: 'Great work team 👏',
    messageType: 'text',
    createdAt: '10:26',
  },
  {
    id: 'msg_3',
    conversationId: 'conv_2',
    senderId: 'user_james',
    senderName: 'James',
    senderAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&auto=format&fit=crop&q=80',
    text: 'project_final.psd',
    messageType: 'document',
    fileName: 'project_final.psd',
    fileSize: '2.4 MB',
    createdAt: '10:28',
  },
  {
    id: 'msg_4',
    conversationId: 'conv_2',
    senderId: 'current_user_id',
    senderName: 'You',
    text: 'Looks perfect! ✅',
    messageType: 'text',
    createdAt: '10:32',
    readBy: ['user_james', 'user_aisha'],
  },
];

export const INITIAL_STATUSES: StatusItem[] = [
  {
    id: 'status_1',
    authorId: 'user_travel_vibes',
    authorName: 'Travel Vibes',
    authorUsername: 'travelvibes',
    authorPhoto: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=500&auto=format&fit=crop&q=80',
    type: 'photo',
    mediaUrl: '/assets/images/zanzibar_beach_1790280962219.jpg',
    text: 'Good vibes only 💛🌊',
    location: 'Zanzibar, Tanzania',
    visibility: 'public',
    likesCount: 1200,
    commentsCount: 342,
    sharesCount: 98,
    createdAt: '2h ago',
    expiresAt: new Date(Date.now() + 22 * 3600 * 1000).toISOString(),
  },
  {
    id: 'status_2',
    authorId: 'user_explore',
    authorName: 'Explore Africa',
    authorUsername: 'explore_af',
    authorPhoto: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=500&auto=format&fit=crop&q=80',
    type: 'poll',
    mediaUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&auto=format&fit=crop&q=80',
    text: 'Where should our next community expedition be? Vote now!',
    location: 'Serengeti, Tanzania',
    visibility: 'public',
    likesCount: 840,
    commentsCount: 112,
    sharesCount: 45,
    createdAt: '4h ago',
    expiresAt: new Date(Date.now() + 20 * 3600 * 1000).toISOString(),
    metadata: {
      pollQuestion: 'Best Safari Destination?',
      pollOptions: [
        { id: 'opt_1', text: 'Serengeti National Park', votes: 420 },
        { id: 'opt_2', text: 'Ngorongoro Crater', votes: 290 },
        { id: 'opt_3', text: 'Mount Kilimanjaro', votes: 130 },
      ],
    },
  },
  {
    id: 'status_3',
    authorId: 'user_foodie',
    authorName: 'Swahili Bites',
    authorUsername: 'swahilibites',
    authorPhoto: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=500&auto=format&fit=crop&q=80',
    type: 'food',
    mediaUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1200&auto=format&fit=crop&q=80',
    text: 'Fresh seafood platter straight from the coast! 🍤 Order with 20% off.',
    location: 'Dar es Salaam, Tanzania',
    visibility: 'public',
    likesCount: 615,
    commentsCount: 89,
    sharesCount: 33,
    createdAt: '6h ago',
    expiresAt: new Date(Date.now() + 18 * 3600 * 1000).toISOString(),
    metadata: {
      discount: '20% OFF TODAY',
      price: 35000,
      currency: 'TZS',
    },
  },
];

export const INITIAL_PRODUCTS: ProductItem[] = [
  {
    id: 'prod_1',
    sellerId: 'seller_tech',
    sellerName: 'SoundWave Hub',
    name: 'Wireless Earbuds',
    description: 'Ultra-low latency Bluetooth 5.4 wireless earbuds with active noise cancellation and 36-hour charging case battery.',
    price: 85000,
    currency: 'TZS',
    images: ['/assets/images/wireless_earbuds_1790280984496.jpg'],
    stock: 24,
    category: 'Electronics',
    location: 'Dar es Salaam',
    rating: 4.8,
    reviewsCount: 124,
    status: 'active',
    createdAt: '2026-03-01T10:00:00Z',
  },
  {
    id: 'prod_2',
    sellerId: 'seller_tech',
    sellerName: 'NextGen Gadgets',
    name: 'Smart Watch Pro',
    description: 'AMOLED display, heart rate tracking, GPS workout monitoring, and water resistance up to 50 meters.',
    price: 120000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80'],
    stock: 15,
    category: 'Electronics',
    location: 'Nairobi',
    rating: 4.7,
    reviewsCount: 90,
    status: 'active',
    createdAt: '2026-03-05T12:00:00Z',
  },
  {
    id: 'prod_3',
    sellerId: 'seller_fashion',
    sellerName: 'AfroStyle Boutique',
    name: 'Handcrafted Kitenge Jacket',
    description: 'Tailored premium cotton jacket with authentic contemporary African print and double-stitched lining.',
    price: 95000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&auto=format&fit=crop&q=80'],
    stock: 8,
    category: 'Fashion',
    location: 'Arusha',
    rating: 4.9,
    reviewsCount: 48,
    status: 'active',
    createdAt: '2026-03-08T15:00:00Z',
  },
  {
    id: 'prod_4',
    sellerId: 'seller_beauty',
    sellerName: 'Botanical Glow',
    name: 'Organic Shea & Baobab Oil Serum',
    description: 'Cold-pressed organic moisturizing blend formulated for deep hydration and youthful skin renewal.',
    price: 45000,
    currency: 'TZS',
    images: ['https://images.unsplash.com/photo-1608248597359-00d9b50dbd6a?w=800&auto=format&fit=crop&q=80'],
    stock: 35,
    category: 'Beauty',
    location: 'Zanzibar',
    rating: 4.9,
    reviewsCount: 160,
    status: 'active',
    createdAt: '2026-03-10T09:00:00Z',
  },
];

export const INITIAL_EVENTS: EventItem[] = [
  {
    id: 'event_1',
    hostId: 'host_fest',
    hostName: 'Kenya Events',
    title: 'Music Festival 2026',
    description: 'The biggest music festival in East Africa! Featuring over 20 top afrobeat and amapiano artists, delicious food stalls, and immersive stage art.',
    bannerUrl: '/assets/images/concert_festival_1790280974630.jpg',
    date: 'Sat, 26 Apr 2026',
    time: '5:00 PM - 2:00 AM',
    location: 'Nairobi, Kenya',
    generalAdmissionPrice: 50000,
    vipPrice: 120000,
    currency: 'TZS',
    categories: ['Music', 'Nightlife', 'Culture'],
    attendeesCount: 3420,
    createdAt: '2026-02-15T00:00:00Z',
  },
  {
    id: 'event_2',
    hostId: 'host_tech',
    hostName: 'Silicon Savannah',
    title: 'East Africa Tech Summit',
    description: 'Join 1,000+ software founders, venture investors, and AI creators discussing the future of tech and fin-tech across the continent.',
    bannerUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&auto=format&fit=crop&q=80',
    date: 'Fri, 15 May 2026',
    time: '9:00 AM - 6:00 PM',
    location: 'Dar es Salaam Serena Hall',
    generalAdmissionPrice: 30000,
    vipPrice: 90000,
    currency: 'TZS',
    categories: ['Tech', 'Conference', 'Networking'],
    attendeesCount: 980,
    createdAt: '2026-02-20T00:00:00Z',
  },
];

export const INITIAL_JOBS: JobItem[] = [
  {
    id: 'job_1',
    posterId: 'company_tech_solutions',
    title: 'Frontend Developer',
    company: 'Tech Solutions',
    companyLogo: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=500&auto=format&fit=crop&q=80',
    location: 'Nairobi, Kenya (Hybrid)',
    jobType: 'Full-time',
    salaryRange: 'TZS 800K - 1.2M',
    currency: 'TZS',
    description: 'We are seeking an experienced React & TypeScript developer with an eye for modern UI aesthetics to join our fast-paced product engineering squad.',
    requirements: ['3+ years with React & TypeScript', 'Experience with state management and real-time APIs', 'Demonstrated UI design sense'],
    tags: ['React', 'TypeScript', 'Tailwind', 'WebSockets'],
    createdAt: '2h ago',
    applicantsCount: 14,
  },
  {
    id: 'job_2',
    posterId: 'company_global_media',
    title: 'Marketing Assistant',
    company: 'Global Media',
    companyLogo: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=500&auto=format&fit=crop&q=80',
    location: 'Remote',
    jobType: 'Part-time',
    salaryRange: 'TZS 400K - 700K',
    currency: 'TZS',
    description: 'Help coordinate influencer campaigns, prepare social media schedules, analyze engagement metrics, and draft engaging newsletters.',
    requirements: ['Familiarity with creator analytics', 'Strong copywriting skills in English & Swahili'],
    tags: ['Marketing', 'Social Media', 'Growth'],
    createdAt: '3h ago',
    applicantsCount: 28,
  },
  {
    id: 'job_3',
    posterId: 'company_creative_hub',
    title: 'Graphic Designer',
    company: 'Creative Hub',
    companyLogo: 'https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=500&auto=format&fit=crop&q=80',
    location: 'Dar es Salaam, Tanzania',
    jobType: 'Full-time',
    salaryRange: 'TZS 500K - 800K',
    currency: 'TZS',
    description: 'Design brand identities, motion assets, and digital marketing materials for leading retail brands in East Africa.',
    tags: ['Figma', 'Photoshop', 'Illustrator'],
    createdAt: '5h ago',
    applicantsCount: 19,
  },
  {
    id: 'job_4',
    posterId: 'company_market_pro',
    title: 'Sales Executive',
    company: 'MarketPro',
    companyLogo: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=500&auto=format&fit=crop&q=80',
    location: 'Nairobi, Kenya',
    jobType: 'Full-time',
    salaryRange: 'TZS 600K - 900K',
    currency: 'TZS',
    description: 'Drive B2B merchant acquisition, onboarding, and relationship management for our expanding digital commerce ecosystem.',
    tags: ['Sales', 'B2B', 'Negotiation'],
    createdAt: '6h ago',
    applicantsCount: 9,
  },
];

export const INITIAL_COMMUNITIES: CommunityItem[] = [
  {
    id: 'comm_1',
    name: 'Tech Innovators',
    description: 'A community for tech enthusiasts, creators, and innovators shaping digital products.',
    iconUrl: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=500&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1200&auto=format&fit=crop&q=80',
    category: 'Technology',
    membersCount: 24500,
    createdBy: 'user_daniel',
    isJoined: true,
    createdAt: '2026-01-10T00:00:00Z',
  },
  {
    id: 'comm_2',
    name: 'Local Food & Flavors',
    description: 'Discover the freshest local eateries, secret recipes, food festivals, and chef showcases.',
    iconUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=500&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1200&auto=format&fit=crop&q=80',
    category: 'Food & Dining',
    membersCount: 45000,
    createdBy: 'user_chef_ali',
    isJoined: false,
    createdAt: '2026-01-15T00:00:00Z',
  },
  {
    id: 'comm_3',
    name: 'Travel & Adventure',
    description: 'Backpackers, island hoppers, and wildlife photographers sharing trails, budgets, and tips.',
    iconUrl: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=500&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1200&auto=format&fit=crop&q=80',
    category: 'Travel',
    membersCount: 78000,
    createdBy: 'user_jane',
    isJoined: false,
    createdAt: '2026-01-20T00:00:00Z',
  },
];

export const INITIAL_TRANSACTIONS: WalletTransaction[] = [
  {
    id: 'tx_1',
    userId: 'current_user_id',
    type: 'receive',
    amount: 50000,
    currency: 'TZS',
    title: 'Payment received',
    counterparty: 'Sarah Mwangi',
    status: 'completed',
    timestamp: '2h ago',
  },
  {
    id: 'tx_2',
    userId: 'current_user_id',
    type: 'purchase',
    amount: -12000,
    currency: 'TZS',
    title: 'Product purchase',
    counterparty: 'SoundWave Hub',
    status: 'completed',
    timestamp: '5h ago',
  },
  {
    id: 'tx_3',
    userId: 'current_user_id',
    type: 'send',
    amount: -25000,
    currency: 'TZS',
    title: 'Sent to Mobile Money',
    counterparty: 'M-Pesa 0755***123',
    status: 'completed',
    timestamp: '1d ago',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_1',
    userId: 'current_user_id',
    title: 'Sarah Mwangi liked your status',
    message: 'Sarah Mwangi reacted with ❤️ to your story',
    type: 'reaction',
    read: false,
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=500&auto=format&fit=crop&q=80',
    createdAt: '2m ago',
  },
  {
    id: 'notif_2',
    userId: 'current_user_id',
    title: 'You have a new message',
    message: 'Sarah Mwangi: Hey! How are you doing? 😊',
    type: 'message',
    read: false,
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=500&auto=format&fit=crop&q=80',
    createdAt: '5m ago',
  },
  {
    id: 'notif_3',
    userId: 'current_user_id',
    title: 'Event reminder: Music Festival 2026',
    message: 'Your upcoming event starts on Sat, 26 Apr 2026 at 5:00 PM',
    type: 'event',
    read: true,
    avatar: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=500&auto=format&fit=crop&q=80',
    createdAt: '12m ago',
  },
  {
    id: 'notif_4',
    userId: 'current_user_id',
    title: 'John followed you',
    message: 'John Doe started following your creator profile',
    type: 'follow',
    read: true,
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=500&auto=format&fit=crop&q=80',
    createdAt: '18m ago',
  },
  {
    id: 'notif_5',
    userId: 'current_user_id',
    title: 'Order #12345 has been shipped',
    message: 'Your Wireless Earbuds package is on the way!',
    type: 'order',
    read: true,
    avatar: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=500&auto=format&fit=crop&q=80',
    createdAt: '32m ago',
  },
  {
    id: 'notif_6',
    userId: 'current_user_id',
    title: 'New job match for your profile',
    message: 'Tech Solutions is hiring for Frontend Developer',
    type: 'job',
    read: true,
    avatar: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=500&auto=format&fit=crop&q=80',
    createdAt: '1h ago',
  },
];
